name: Build and deploy Node.js app to Azure Web App - Petcare-Web

on:
  push:
    branches:
      - main
      - feature/infra
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build  # Usa o Vite para buildar a aplicação
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./aplicacao-petcare/dist -r  # Zipa a pasta dist, onde o Vite coloca o build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8E70F13B72234938851988F681AD8D87 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7658F0B18C364334A2A923E1DD105CED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AEC5F2DE4BCD4A56B727B98BA5357A60 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Petcare-Web'
          slot-name: 'Production'
          package: ./release.zip  # Deploy o arquivo zipado gerado
